# Generated by Django 3.2.6 on 2022-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
